export const PRODUCTS = {
  mistCollection: [
    {
      id: "imperial-mist",
      name: "Imperial Mist",
      description: "A majestic blend of regal oud and amber, commanding attention.",
      price: 449,
      color: "#8B5E3C",
      accentColor: "#F21D2F",
      notes: ["Oud", "Amber", "Sandalwood"],
      image: "/images/im.jpeg",
      model: "/models/bottle.glb",
    },
    {
      id: "regal-blend",
      name: "Regal Blend",
      description: "Sophisticated notes of leather and cedar for the refined connoisseur.",
      price: 449,
      color: "#2C1810",
      accentColor: "#8B7355",
      notes: ["Leather", "Cedar", "Musk"],
      image: "/images/rb.jpeg",
      model: "/models/bottle.glb",
    },
    {
      id: "vogue-vallet",
      name: "Vogue Vallet",
      description: "Parisian elegance captured in every mist, floral and daring.",
      price: 449,
      color: "#4A1942",
      accentColor: "#C9A0DC",
      notes: ["Rose", "Peony", "Iris"],
      image: "/images/vv.jpeg",
      model: "/models/bottle.glb",
    },
    {
      id: "mosidh-seduction",
      name: "Mosidh Seduction",
      description: "An intoxicating allure of vanilla, jasmine, and warm musk.",
      price: 449,
      color: "#1A0A2E",
      accentColor: "#9B59B6",
      notes: ["Vanilla", "Jasmine", "Musk"],
      image: "/images/p4.jpeg",
      model: "/models/bottle.glb",
    },
  ],
  hangingCollection: [
    {
      id: "new-ride-luxe",
      name: "New Ride Luxe",
      description: "The scent of new beginnings, fresh and exhilarating.",
      price: 349,
      color: "#0A1628",
      accentColor: "#3498DB",
      notes: ["Ocean", "Mint", "Cedar"],
      image: "/images/p5.jpeg",
    },
    {
      id: "green-muse",
      name: "Green Muse",
      description: "Nature's finest essences, refreshing and invigorating.",
      price: 349,
      color: "#0A2818",
      accentColor: "#27AE60",
      notes: ["Basil", "Eucalyptus", "Moss"],
      image: "/images/gm.jpeg",
    },
    {
      id: "earth-realm",
      name: "Earth Realm",
      description: "Grounding woody notes that connect you to nature.",
      price: 349,
      color: "#2C1A0E",
      accentColor: "#8D6E4C",
      notes: ["Vetiver", "Patchouli", "Oak"],
      image: "/images/p7.jpeg",
    },
    {
      id: "passion-tropic",
      name: "Passion Tropic",
      description: "Tropical escape with exotic fruits and warm spices.",
      price: 349,
      color: "#2E0A1A",
      accentColor: "#E74C3C",
      notes: ["Passion Fruit", "Coconut", "Spice"],
      image: "/images/pt.jpeg",
    },
  ],
};

export const SCENT_NOTES = [
  { name: "Wood", icon: "🪵", color: "#8B5E3C", particles: "Woody warmth lingers" },
  { name: "Leather", icon: "🧥", color: "#4A3728", particles: "Rich sophistication" },
  { name: "Ocean", icon: "🌊", color: "#2980B9", particles: "Fresh sea breeze" },
  { name: "Amber", icon: "✨", color: "#F21D2F", particles: "Bold warmth" },
  { name: "Citrus", icon: "🍊", color: "#E67E22", particles: "Vibrant zest" },
  { name: "Vanilla", icon: "🌿", color: "#F5DEB3", particles: "Sweet elegance" },
  { name: "Flowers", icon: "🌸", color: "#C9A0DC", particles: "Blooming beauty" },
];

export const FEATURES = [
  {
    title: "Long Lasting Fragrance",
    description: "Up to 45 days of continuous luxury fragrance in your car.",
    icon: "Clock",
  },
  {
    title: "Premium Quality",
    description: "Crafted with the finest ingredients sourced from around the world.",
    icon: "Gem",
  },
  {
    title: "Stylish Packaging",
    description: "Each bottle is a statement piece, designed for the discerning eye.",
    icon: "Gift",
  },
  {
    title: "Universal Fit",
    description: "Designed to complement every car interior, from sedans to SUVs.",
    icon: "Car",
  },
];
